### ISSUE TITLE
Why are we rewriting something that already exists?

### ISSUE THREAD

**Issue by mickypaganini** [dguest/btag-training#6]
Hi friends! 
Sorry I couldn't be here yesterday during the hands on session. I'm confused by what's going on in this repository. Why are we rewriting a NN training and evaluation? We already have all of that.

**Comment by matthewfeickert** [comment]
@mickypaganini @dguest @rccreager I think that things aren't very well established. Can we discuss over the break/lunch and then setup a roadmap for the afternoon and tomorrow?

**Comment by dguest** [comment]
Can I close this?
